### ISSUE TITLE
Missing Company Type

### ISSUE THREAD

**Issue by MattHemus** [kevbite/CompaniesHouse.NET#126] opened 2020-05-04 07:28 UTC
Hi,

Could you add the following Company Type to the enum;

further-education-or-sixth-form-college-corporation

An example company that returns this WEST KENT & ASHFORD COLLEGE, FE000001.

The missing enum is currently causing an exception when requesting this company.

Many Thanks

Matt

**Comment by kevbite** [comment] 2020-05-04 10:33
I've just pushed a release with this in. It's in version [7.6.2](https://www.nuget.org/packages/CompaniesHouse/7.6.2).

**Comment by MattHemus** [comment] 2020-05-04 10:38
That’s great, thanks for the quick turnaround.

Matt

**Comment by kevbite** [comment] 2020-05-04 10:44
Closing as the issue is fixed.

**Closed by kevbite** 2020-05-04 10:44 UTC
Labels: enhancement
